FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ ./src/
COPY templates/ ./templates/
RUN mkdir -p models
EXPOSE 5001
ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=src/app.py
CMD ["python", "src/app.py"]